apiVersion: batch/v1
kind: Job
metadata:
  name: k6-loadtest
  namespace: ecommerce
spec:
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command:
            ["k6", "run", "-e", "MODE=cluster", "/scripts/k6-loadtest.js"]
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: k6-script
              mountPath: /scripts
      volumes:
        - name: k6-script
          configMap:
            name: k6-script
      restartPolicy: Never
  backoffLimit: 0
